language: php

services:
  - mysql
  - postgresql

matrix:
 include:
   # Older PHP versions not supported by travis.
  - php: 5.6
    dist: xenial
  - php: 7.0
    dist: xenial
  - php: 7.1
    dist: bionic
  - php: 7.2
    dist: bionic
  - php: 7.3
    dist: bionic
  - php: 7.4
    dist: bionic
  - php: 8.0
    dist: bionic
  - php: 8.1
    dist: bionic
  - php: 8.2
    dist: focal
  - php: 8.3
    dist: bionic
  - php: 8.4
    dist: noble
    allow_failures: true
  - php: 8.5
    dist: noble
    allow_failures: true

env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost
  - XDEBUG_MODE=coverage

before_install:
  - if [[ "$TRAVIS_DIST" == "focal" ]]; then sudo apt-get install libonig5 ;fi
  - if [[ "$TRAVIS_DIST" == "focal" ]]; then sudo service postgresql restart ;fi

before_script:
  - touch /tmp/oodb.db
  - mysql -e 'create database oodb;'
  - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - psql -c 'create database oodb;' -U postgres
  - php replica2.php onlyphp
  - cp rb.php testing/cli/testcontainer/rb.php
  - cd testing/cli


script: php runtests.php
