language: php
php:
  - 5.3
  - 5.4

before_script:
  - echo 'yes' | sudo add-apt-repository ppa:cubrid/cubrid
  - sudo apt-get update
  - sudo apt-get install cubrid
  - /etc/profile.d/cubrid.sh
  - sudo apt-get install cubrid-demodb
  - sudo apt-get install php5-cubrid
  - /etc/profile.d/cubrid.sh
  - cubrid service start
  - cubrid server start demodb  
  - touch /tmp/oodb.db
  - mysql -e 'create database oodb;'
  - psql -c 'create database oodb;' -U postgres
  - php replica.php
  - cp rb.php testing/cli/testcontainer/rb.php  
  - cd testing/cli
    
 
script: ./startnc.sh
